### PR TITLE
Feature/rdm

### PR DESCRIPTION
**Pull request by justus-reihs**
Tackles #10.

Not ready yet, just started 🚀 .

Stay tuned 👀

### CODE REVIEW

**Comment by justus-reihs** [comment]
@lnnrtwttkhn, GitHub detected an code spell error, but it isn't $\rightarrow$ Paul Groth is really named Groth and not Growth.
How can I handle this?

**Comment by lnnrtwttkhn** [comment]
> How can I handle this?

I [let `.codespellrc ignore *.bib](https://github.com/lnnrtwttkhn/repro-book/pull/38/commits/3824bdcbab99af9da9a5845ca7eb8b09cdf70784) which makes a lot of sense exactly because of these types of "errors".

**Comment by justus-reihs** [comment]
@lnnrtwttkhn
- [ ] Fix Codespell error for **J**ava**S**cript **O**bject **N**otation

**Comment by lnnrtwttkhn** [comment]
Great work @justus-reihs, thank you! Ready to merge this initial version. While reviewing I added a few ideas for later in #45.

**Pull request merged**
