### PR TITLE
9 add chapter on good coding practices

### PR DESCRIPTION
**Pull request by justus-reihs**
For the start, this is okay, in my opinion. I will later dive deeper into the topic. I think its more useful, when I start from the beginning, because I don't know yet what the students will have learned when they are reading the chapter on good coding practices.

### CODE REVIEW

**Comment by justus-reihs** [comment]
Hey @lnnrtwttkhn, I just finished my first draft on #9 🎉 . I am looking forward to your feedback.

**Comment by lnnrtwttkhn** [comment]
Awesome, very nice chapter, thanks @justus-reihs!
I made a bunch of smaller changes in [9a8f5f2](https://github.com/lnnrtwttkhn/repro-book/pull/25/commits/9a8f5f22c61cef0da032e20200e69c82accb5a56).
Here are a few ideas to add in: 

- [ ] Add info about the `here` package in R to section on paths (see e.g., [here](https://github.com/jennybc/here_here))
- [ ] Add all source to `references.bib` file and use citation (see [Quarto docs](https://quarto.org/docs/authoring/citations.html))
- [ ] Add "Do" and "Don't" code examples next to each other, like in the following. I did it once for the section on "Names" in the code style section. Please add for all other instances.


````
:::: columns
::: {.column width="49%"}
```{r filename="Strive for"}
#| eval: false
short_flights <- flights |>
  filter(air_time < 60)
```
:::
::: {.column width="2%"}
:::
::: {.column width="49%"}
```{r filename="Avoid"}
#| eval: false
SHORTFLIGHTS <- flights |>
  filter(air_time < 60)
```
::::
````

- [ ] ">Here a cartoon illustrating how the pipe works would be fun." Cartoon missing?
- [ ] Add collapsed callout box about difference between `|>` and `%>%` pipe operators.
- [ ] Show example where `verify` fails (I guess this error then has to be ignored by Quarto so that the rendering does not fail.
- [ ] Add this to indicate code example that can be copied:

````
```{r filename="Code"}
````

- [ ] Not urgent for now, but it could be useful to find a way to reuse the data in later chapters, e.g., by saving the dataframe.

**Comment by justus-reihs** [comment]
Thank for your reply @lnnrtwttkhn.
Implemented your ideas ✅ 
A cartoon is still missing, I haven't found a good one yet. Do you know some resources where I could search?

**Comment by lnnrtwttkhn** [comment]
Thanks for the additional changes @justus-reihs!

I didn't quite get this part when talking about tidy data:

> However, this rule of thumb does not always apply, for example when data is rearranged.

But I would still merge this now and we can take another look at it later! 🚀

**Pull request merged**
